// Build the design system from Figma-exported tokens. Zero dependencies.
//
// Reads:  tokens/primitives.tokens.json   (raw color scales — the foundation)
//         tokens/semantic.tokens.json      (roles that reference primitives)
// Emits:  dist/variables.css               (CSS custom properties — the usable output)
//         dist/tokens.resolved.json         (flat, resolved values)
//         docs/data.js                      (data for the documentation page)
//
// Run: npm run build   (or: node scripts/build.mjs)

import { readFileSync, writeFileSync, mkdirSync } from "node:fs";
import { fileURLToPath } from "node:url";
import { dirname, join } from "node:path";

const root = join(dirname(fileURLToPath(import.meta.url)), "..");
const read = (p) => JSON.parse(readFileSync(join(root, p), "utf8"));

const primitivesDoc = read("tokens/primitives.tokens.json");
const semanticDoc = read("tokens/semantic.tokens.json");

// slug: a token path -> css var name.  "gray.500" -> "gray-500", "text.dark-950" -> "text-dark-950"
const slug = (path) => path.replace(/\./g, "-").toLowerCase();

// ---- 1. Flatten primitives -----------------------------------------------
// A primitive leaf is a node with $value = { hex, ... }. Families nest one level.
const primitives = []; // { family, step, path, var, hex }
const primitiveHex = {}; // "gray.500" -> "#6A7282"

for (const [family, node] of Object.entries(primitivesDoc)) {
  if (family.startsWith("$")) continue;
  if (node.$value && typeof node.$value === "object" && node.$value.hex) {
    // single color (white, black, transparent)
    const hex = node.$value.hex;
    const alpha = node.$value.alpha;
    primitiveHex[family] = family === "transparent" ? "transparent" : hex;
    primitives.push({ family, step: null, path: family, var: slug(family), hex: alpha === 0 ? "transparent" : hex });
    continue;
  }
  for (const [step, leaf] of Object.entries(node)) {
    if (step.startsWith("$")) continue;
    const hex = leaf.$value?.hex;
    if (!hex) continue;
    primitiveHex[`${family}.${step}`] = hex;
    primitives.push({ family, step, path: `${family}.${step}`, var: slug(`${family}.${step}`), hex });
  }
}

// group primitives by family, in source order
const primitiveScales = [];
for (const p of primitives) {
  if (p.step === null) continue; // skip singletons in the scale grid
  let scale = primitiveScales.find((s) => s.family === p.family);
  if (!scale) { scale = { family: p.family, steps: [] }; primitiveScales.push(scale); }
  scale.steps.push({ step: p.step, var: p.var, hex: p.hex });
}

// ---- 2. Resolve semantic tokens ------------------------------------------
// A semantic leaf: { $value: "{gray.950}", $description: "gray.950 · #030712" }
const refPath = (v) => String(v).replace(/[{}]/g, "");

const semanticGroups = []; // { group, tokens: [{ name, path, var, refPath, refVar, hex }] }

for (const [group, node] of Object.entries(semanticDoc)) {
  if (group.startsWith("$")) continue;
  const tokens = [];
  for (const [name, leaf] of Object.entries(node)) {
    if (name.startsWith("$") || !leaf || !leaf.$value) continue;
    const ref = refPath(leaf.$value);
    const hex = primitiveHex[ref] ?? (leaf.$description?.split("·")[1]?.trim()) ?? "";
    tokens.push({
      name,
      path: `${group}.${name}`,
      var: slug(`${group}.${name}`),
      refPath: ref,
      refVar: slug(ref),
      hex,
    });
  }
  if (tokens.length) semanticGroups.push({ group, tokens });
}

// ---- 3. Emit dist/variables.css ------------------------------------------
const q = (v) => v; // hex values are already safe
let css = "/* Design system tokens — generated by scripts/build.mjs. Do not edit by hand. */\n\n:root {\n";
css += "  /* ---------- Primitives ---------- */\n";
for (const p of primitives) css += `  --${p.var}: ${q(p.hex)};\n`;
css += "\n  /* ---------- Semantic ---------- */\n";
for (const g of semanticGroups) {
  css += `  /* ${g.group} */\n`;
  for (const t of g.tokens) css += `  --${t.var}: var(--${t.refVar});\n`;
}
css += "}\n";

mkdirSync(join(root, "dist"), { recursive: true });
writeFileSync(join(root, "dist/variables.css"), css);

// ---- 4. Emit resolved JSON + docs data -----------------------------------
const resolved = {
  primitives: Object.fromEntries(primitives.map((p) => [p.path, p.hex])),
  semantic: Object.fromEntries(
    semanticGroups.flatMap((g) => g.tokens.map((t) => [t.path, { ref: t.refPath, hex: t.hex }]))
  ),
};
writeFileSync(join(root, "dist/tokens.resolved.json"), JSON.stringify(resolved, null, 2) + "\n");

const pageData = { semanticGroups, primitiveScales };
mkdirSync(join(root, "public"), { recursive: true });
writeFileSync(join(root, "public/data.js"), "window.DS = " + JSON.stringify(pageData, null, 2) + ";\n");

// ---- 5. Emit the shadcn registry -----------------------------------------
// registry.json (manifest, hand-edited) -> public/r/<name>.json (installable
// item, with generated cssVars) + public/r/registry.json (the index).
// This is a real shadcn registry item: `npx shadcn add <host>/r/tokens.json`.
const manifest = read("registry.json");

// cssVars.theme: mode-agnostic CSS variables. Keys carry NO leading `--`.
// Primitives resolve to hex; semantic tokens reference their primitive.
const themeVars = {};
for (const p of primitives) themeVars[p.var] = p.hex;
for (const g of semanticGroups) for (const t of g.tokens) themeVars[t.var] = `var(--${t.refVar})`;

mkdirSync(join(root, "public/r"), { recursive: true });
const indexItems = [];
for (const meta of manifest.items ?? []) {
  const item = {
    $schema: "https://ui.shadcn.com/schema/registry-item.json",
    name: meta.name,
    type: meta.type,
    title: meta.title,
    description: meta.description,
    cssVars: { theme: themeVars },
    files: meta.files ?? [],
  };
  writeFileSync(join(root, `public/r/${meta.name}.json`), JSON.stringify(item, null, 2) + "\n");
  const { name, type, title, description } = meta;
  indexItems.push({ name, type, title, description });
}
writeFileSync(
  join(root, "public/r/registry.json"),
  JSON.stringify({ name: manifest.name, homepage: manifest.homepage, items: indexItems }, null, 2) + "\n"
);

const semCount = semanticGroups.reduce((n, g) => n + g.tokens.length, 0);
const varCount = Object.keys(themeVars).length;
console.log(
  `✓ dist/variables.css        ${primitives.length} primitives + ${semCount} semantic` +
  `\n✓ dist/tokens.resolved.json` +
  `\n✓ public/data.js            ${primitiveScales.length} scales, ${semanticGroups.length} semantic groups` +
  `\n✓ public/r/*.json           ${manifest.items.length} registry item(s), ${varCount} cssVars` +
  `\n✓ public/r/registry.json    index`
);
